// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//学生数据体
type Student struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Classes              string   `protobuf:"bytes,3,opt,name=classes,proto3" json:"classes,omitempty"`
	Grade                int32    `protobuf:"varint,4,opt,name=grade,proto3" json:"grade,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetClasses() string {
	if m != nil {
		return m.Classes
	}
	return ""
}

func (m *Student) GetGrade() int32 {
	if m != nil {
		return m.Grade
	}
	return 0
}

//请求数据体定义
type StudentRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StudentRequest) Reset()         { *m = StudentRequest{} }
func (m *StudentRequest) String() string { return proto.CompactTextString(m) }
func (*StudentRequest) ProtoMessage()    {}
func (*StudentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *StudentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentRequest.Unmarshal(m, b)
}
func (m *StudentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentRequest.Marshal(b, m, deterministic)
}
func (m *StudentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentRequest.Merge(m, src)
}
func (m *StudentRequest) XXX_Size() int {
	return xxx_messageInfo_StudentRequest.Size(m)
}
func (m *StudentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StudentRequest proto.InternalMessageInfo

func (m *StudentRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Student)(nil), "message.Student")
	proto.RegisterType((*StudentRequest)(nil), "message.StudentRequest")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x7c, 0xb9,
	0xd8, 0x83, 0x4b, 0x4a, 0x53, 0x52, 0xf3, 0x4a, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53,
	0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x09, 0x2e, 0xf6, 0xe4, 0x9c, 0xc4,
	0xe2, 0xe2, 0xd4, 0x62, 0x09, 0x66, 0xb0, 0x30, 0x8c, 0x2b, 0x24, 0xc2, 0xc5, 0x9a, 0x5e, 0x94,
	0x98, 0x92, 0x2a, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0xe1, 0x28, 0xa9, 0x70, 0xf1, 0x41,
	0x8d, 0x0b, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0xc6, 0x6a, 0xaa, 0x91, 0x27, 0x5c, 0x55, 0x70, 0x6a,
	0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x39, 0x17, 0x97, 0x7b, 0x6a, 0x09, 0xcc, 0x25, 0xe2, 0x7a,
	0x30, 0xd7, 0xa2, 0x1a, 0x26, 0x25, 0x80, 0x2e, 0x91, 0xc4, 0x06, 0xf6, 0x8f, 0x31, 0x20, 0x00,
	0x00, 0xff, 0xff, 0xfd, 0x08, 0x8b, 0x49, 0xe0, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for StudentService service

type StudentServiceClient interface {
	//查询学生信息服务
	GetStudent(ctx context.Context, in *StudentRequest, opts ...client.CallOption) (*Student, error)
}

type studentServiceClient struct {
	c           client.Client
	serviceName string
}

func NewStudentServiceClient(serviceName string, c client.Client) StudentServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "message"
	}
	return &studentServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *studentServiceClient) GetStudent(ctx context.Context, in *StudentRequest, opts ...client.CallOption) (*Student, error) {
	req := c.c.NewRequest(c.serviceName, "StudentService.GetStudent", in)
	out := new(Student)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for StudentService service

type StudentServiceHandler interface {
	//查询学生信息服务
	GetStudent(context.Context, *StudentRequest, *Student) error
}

func RegisterStudentServiceHandler(s server.Server, hdlr StudentServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&StudentService{hdlr}, opts...))
}

type StudentService struct {
	StudentServiceHandler
}

func (h *StudentService) GetStudent(ctx context.Context, in *StudentRequest, out *Student) error {
	return h.StudentServiceHandler.GetStudent(ctx, in, out)
}
